# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Annotate_Console.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1680, 1050)
        MainWindow.setMinimumSize(QtCore.QSize(1680, 1050))
        MainWindow.setMaximumSize(QtCore.QSize(1680, 1050))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/YY.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.m4_ShowImage = QtWidgets.QLabel(self.centralwidget)
        self.m4_ShowImage.setEnabled(True)
        self.m4_ShowImage.setGeometry(QtCore.QRect(0, 10, 1231, 921))
        self.m4_ShowImage.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.m4_ShowImage.setAutoFillBackground(False)
        self.m4_ShowImage.setFrameShape(QtWidgets.QFrame.Box)
        self.m4_ShowImage.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.m4_ShowImage.setText("")
        self.m4_ShowImage.setPixmap(QtGui.QPixmap(":/pic/YY.jpg"))
        self.m4_ShowImage.setScaledContents(True)
        self.m4_ShowImage.setObjectName("m4_ShowImage")
        self.m4_OpenVideo_Btn = QtWidgets.QPushButton(self.centralwidget)
        self.m4_OpenVideo_Btn.setEnabled(False)
        self.m4_OpenVideo_Btn.setGeometry(QtCore.QRect(1250, 30, 181, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.m4_OpenVideo_Btn.setFont(font)
        self.m4_OpenVideo_Btn.setObjectName("m4_OpenVideo_Btn")
        self.m4_CloseVideo_Btn = QtWidgets.QPushButton(self.centralwidget)
        self.m4_CloseVideo_Btn.setEnabled(False)
        self.m4_CloseVideo_Btn.setGeometry(QtCore.QRect(1250, 90, 181, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.m4_CloseVideo_Btn.setFont(font)
        self.m4_CloseVideo_Btn.setObjectName("m4_CloseVideo_Btn")
        self.m4_SetSavePath_Btn = QtWidgets.QPushButton(self.centralwidget)
        self.m4_SetSavePath_Btn.setGeometry(QtCore.QRect(1250, 320, 181, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.m4_SetSavePath_Btn.setFont(font)
        self.m4_SetSavePath_Btn.setObjectName("m4_SetSavePath_Btn")
        self.m4_LabelDir = QtWidgets.QLineEdit(self.centralwidget)
        self.m4_LabelDir.setGeometry(QtCore.QRect(1250, 380, 391, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.m4_LabelDir.setFont(font)
        self.m4_LabelDir.setObjectName("m4_LabelDir")
        self.m4_TakePhoto_Btn = QtWidgets.QPushButton(self.centralwidget)
        self.m4_TakePhoto_Btn.setEnabled(False)
        self.m4_TakePhoto_Btn.setGeometry(QtCore.QRect(1250, 150, 181, 51))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.m4_TakePhoto_Btn.setFont(font)
        self.m4_TakePhoto_Btn.setObjectName("m4_TakePhoto_Btn")
        self.m4_SavePath = QtWidgets.QLineEdit(self.centralwidget)
        self.m4_SavePath.setGeometry(QtCore.QRect(1250, 220, 391, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(10)
        self.m4_SavePath.setFont(font)
        self.m4_SavePath.setObjectName("m4_SavePath")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1680, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tool_Annotate"))
        self.m4_OpenVideo_Btn.setText(_translate("MainWindow", "打开相机"))
        self.m4_CloseVideo_Btn.setText(_translate("MainWindow", "关闭相机"))
        self.m4_SetSavePath_Btn.setText(_translate("MainWindow", "设置保存图像目录："))
        self.m4_TakePhoto_Btn.setText(_translate("MainWindow", "拍照"))

import apprcc_rc
